{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "config" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier ) | nindent 4 }}
data:
  application.properties: |
    server.port=8080
    spring.data.mongodb.uri=mongodb://{{ $.Values.database.mongodb.user }}:{{ $.Values.database.mongodb.password }}@{{ $.Values.database.mongodb.host }}:{{ $.Values.database.mongodb.port }}/boomerang
    {{- range $k, $v := $.Values.service }}
    boomerang.bosun.service.{{ $k }}.host={{- include "bmrg.name" (dict "context" $ "tier" "service" "component" $k ) }}
    boomerang.bosun.service.{{ $k }}.root={{ if $.Values.ingress.root }}{{ $.Values.ingress.root }}{{ end }}/{{ $product }}/service/{{ $k }}
    {{- end }}
    {{ include "bmrg.core.services" $ | indent 4 }}
    boomerang.cicd.service.ci.host=http://bmrg-cicd-service-ci
    {{- if $.Values.general.enable.debug }}
    logging.level.org.springframework.web.client.RestTemplate=DEBUG
    logging.level.org.springframework.core.env.PropertySourcesPropertyResolver=DEBUG
    logging.level.root=INFO
    {{- end }}
    swagger.enable={{ $.Values.general.enable.apidocs }}
    boomerang.proxy.enable={{ $.Values.proxy.enable }}
    boomerang.proxy.host={{ $.Values.proxy.host }}
    boomerang.proxy.port={{ $.Values.proxy.port }}
    boomerang.proxy.ignore={{ $.Values.proxy.ignore }}
    opa.host={{- include "bmrg.name" (dict "context" $ "tier" "opa") }}