{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "util" -}}
{{- $component := "data" -}}
{{- if $.Values.job.data.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "tier" $tier "component" $component ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier "component" $component ) | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
spec:
  backoffLimit: 1
  completions: 1
  template:
    metadata:
      labels:
        {{- include "bmrg.labels.standard" (dict "context" . "platform" $platform "product" $product "tier" $tier "component" $component ) | nindent 8 }}
    spec:
      containers:
        - name: "pre-install-{{ $tier }}-cntr"
          image: "{{ $.Values.image.registry }}{{ $.Values.job.data.image.repository }}:{{ $.Values.job.data.image.tag }}"
          imagePullPolicy: "{{ $.Values.image.pullPolicy }}"
          env:
          - name: JAVA_OPTS
            value: "-Dspring.profiles.active={{ $.Values.job.data.profile }} -Dspring.data.mongodb.uri=mongodb://{{ $.Values.database.mongodb.user }}:{{ $.Values.database.mongodb.password }}@{{ $.Values.database.mongodb.host }}:{{ $.Values.database.mongodb.port }}/boomerang"
      imagePullSecrets:
      - name: boomerang.registrykey
      restartPolicy: Never
{{- end }}