{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "web" -}}
{{- if $.Values.ingress.enabled -}}
{{- range $k, $v := $.Values.web }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "tier" $tier "component" $k ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier "component" $k ) | nindent 4 }}
  annotations:
    ingress.kubernetes.io/auth-signin: "{{ $.Values.ingress.auth.url.external }}"
    ingress.kubernetes.io/auth-url: "{{ $.Values.ingress.auth.url.internal }}"
    ingress.kubernetes.io/configuration-snippet: |
      {{- include "bmrg.ingress.config.auth_proxy_access_control" $ | nindent 6 }}
      {{- include "bmrg.ingress.config.auth_proxy_authorization" $ | nindent 6 }}
    ingress.kubernetes.io/ssl-redirect: "true"
    ingress.kubernetes.io/client-max-body-size: 1m
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          {{- if $.Values.ingress.root }}
          - path: {{ $.Values.ingress.root }}/{{ $tier }}/{{ $k }}
          {{- else }}
          - path: /{{ $tier }}/{{ $k }}
          {{- end }}
            backend:
              serviceName: {{ include "bmrg.name" (dict "context" $ "tier" $tier "component" $k ) }}
              servicePort: {{ $platform }}-port-svc
  tls:
    - hosts:
        - {{ $.Values.ingress.host }}
      {{- if $.Values.ingress.tlsSecretName }}
      secretName: {{ $.Values.ingress.tlsSecretName }}
      {{- end }}
---
{{- end }}
{{- end }}