{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "service" -}}
{{- if $.Values.ingress.enabled -}}
{{- range $k, $v := $.Values.service }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "tier" $tier "component" $k ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier "component" $k ) | nindent 4 }}
  annotations:
    ingress.kubernetes.io/configuration-snippet: |
      {{- include "bmrg.ingress.config.auth_proxy_access_control" $ | nindent 6 }}
      {{- include "bmrg.ingress.config.auth_proxy_authorization" $ | nindent 6 }}
      if ($request_method = 'OPTIONS') {
      add_header 'Access-Control-Allow-Origin' $http_origin;
      add_header 'Access-Control-Allow-Credentials' 'true';
      add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,PATCH,DELETE,OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Length' 0;
      add_header 'Content-Type' 'text/plain charset=UTF-8';
      return 204;}
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /{{ $k }}/$2
    ingress.kubernetes.io/client-max-body-size: 1m
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          {{- if $.Values.ingress.root }}
          - path: {{ $.Values.ingress.root }}/{{ $product }}/{{ $tier }}/{{ $k }}(/|$)(.*)
          {{- else }}
          - path: /{{ $product }}/{{ $tier }}/{{ $k }}(/|$)(.*)
          {{- end }}
            backend:
              serviceName:  {{ include "bmrg.name" (dict "context" $ "tier" $tier "component" $k ) }}
              servicePort: {{ $platform }}-port-svc
  tls:
    - hosts:
        - {{ $.Values.ingress.host }}
      {{- if $.Values.ingress.tlsSecretName }}
      secretName: {{ $.Values.ingress.tlsSecretName }}
      {{- end }}
---
{{- end }}
{{- end }}