{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "services" -}}
{{- if $.Values.ingress.enabled -}}
{{- range $k, $v := $.Values.services }}
{{- if eq $k "listener" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "tier" $tier "component" $k ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier "component" $k ) | nindent 4 }}
  annotations:
    ingress.kubernetes.io/auth-url: "{{ $.Values.auth.tokenURL }}"
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: /{{ $k }}/$2
    ingress.kubernetes.io/client-max-body-size: 1m
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ $.Values.ingress.host }}
      http:
        paths:
          - path: {{ if $.Values.ingress.root }}{{ $.Values.ingress.root }}{{- end }}/{{ $product }}/{{ $tier }}/{{ $k }}(/|$)(.*)
            backend:
              serviceName:  {{ include "bmrg.name" (dict "context" $ "tier" $tier "component" $k ) }}
              servicePort: {{ $platform }}-port-svc
  tls:
    - hosts:
        - {{ $.Values.ingress.host }}
      {{- if $.Values.ingress.tlsSecretName }}
      secretName: {{ $.Values.ingress.tlsSecretName }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}