{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "rbac" -}}
{{- $values := .Values -}}
{{- $context := . -}}
{{- if $values.workers.security.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $platform }}-{{ $product }}-worker
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
{{- end }}