{{- if $.Values.workers.security.enable }}
{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "rbac" -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $platform }}:{{ $product }}:worker
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $platform }}:{{ $product }}:worker
subjects:
- kind: ServiceAccount
  name: {{ $platform }}-{{ $product }}-worker
  namespace: {{ $.Release.Namespace }}
{{- end }}