{{- if $values.workers.security.enable }}
{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "rbac" -}}
{{- $values := .Values -}}
{{- $context := . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $platform }}:{{ $product }}:worker
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
rules:
{{- if .Capabilities.APIVersions.Has "security.openshift.io/v1" }}
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ $values.workers.security.policy }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- else }}
- apiGroups:
  - extensions
  resourceNames:
  - {{ $values.workers.security.policy }}
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
{{- end }}