{{- if $values.workers.security.enable }}
{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "rbac" -}}
{{- $values := .Values -}}
{{- $context := . -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $platform }}:{{ $product }}:controller
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $platform }}:{{ $product }}:controller
subjects:
- kind: ServiceAccount
  name: {{ $platform }}-{{ $product }}-controller
  namespace: {{ $.Release.Namespace }}
{{- end }}