{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "secrets" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier ) | nindent 4 }}
type: Opaque
data:
  {{- if not $.Values.database.mongodb.secretName }}
  MONGODB_PASSWORD: {{ $.Values.database.mongodb.password | b64enc }}
  {{- end }}