{{- $platform := "bmrg" -}}
{{- $product := "auth" -}}
{{- $component := "config" -}}
{{- $tier := "htpasswd" -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "component" $component "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "component" $component "tier" $tier  ) | nindent 4 }}
data:
  htpasswd: |
    bmrgadmin:$2y$05$88dgk3Kl/r9dLVu7RiDreOiPYU325DW4/KeC7xPvTrmsLdfGyfX8e
