{{- $platform := "bmrg" -}}
{{- $product := "auth" -}}
{{- $tier := "secrets" -}}
{{- if $.Values.auth.displayHtpasswdForm }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier ) | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  UPSTREAM_AUTH_PASSWORD: {{ "coronet-cottage-nave-idiom-resume" | b64enc }}
{{- end }}