{{- $platform := "bmrg" -}}
{{- $product := "auth" -}}
{{- $component := "config" -}}
{{- $tier := "allowemail" -}}
{{- if and ($.Values.authorization.allowEmailList.enabled) (eq .Values.authorization.allowEmailList.persistence "secret") }}
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "component" $component "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "component" $component "tier" $tier  ) | nindent 4 }}
data:
  authenticated-emails-list: |
    {{ include "bmrg.util.joinListWithNL" .Values.authorization.allowEmailList.emailList | b64enc }}
{{- end }}
